version: "3.8"

services:
  bitcoind:
    image: bitcoin/bitcoin:latest
    container_name: bitcoind
    command: >
      bitcoind
      -regtest=1
      -server=1
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -txindex=1
      -fallbackfee=0.0002
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "18443:18443"
    volumes:
      - bitcoind_data:/bitcoin
    networks:
      - lnnet

  lnd1:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: lnd1
    command: >
      lnd
      --noseedbackup
      --alias=lnd1
      --bitcoin.active
      --bitcoin.regtest
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind:18443
      --bitcoind.rpcuser=bitcoin
      --bitcoind.rpcpass=bitcoin
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --tlsextraip=0.0.0.0
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --listen=0.0.0.0:9735
      --debuglevel=info
    ports:
      - "8080:8080"
      - "10009:10009"
      - "9735:9735"
    volumes:
      - ./lnd1-data:/root/.lnd
    depends_on:
      - bitcoind
    networks:
      - lnnet

  lnd2:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: lnd2
    command: >
      lnd
      --noseedbackup
      --alias=lnd2
      --bitcoin.active
      --bitcoin.regtest
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind:18443
      --bitcoind.rpcuser=bitcoin
      --bitcoind.rpcpass=bitcoin
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --tlsextraip=0.0.0.0
      --rpclisten=0.0.0.0:10010
      --restlisten=0.0.0.0:8081
      --listen=0.0.0.0:9736
      --debuglevel=info
    ports:
      - "8081:8081"
      - "10010:10010"
      - "9736:9736"
    volumes:
      - ./lnd2-data:/root/.lnd
    depends_on:
      - bitcoind
    networks:
      - lnnet


volumes:
  bitcoind_data:
  lnd2_data:

networks:
  lnnet:
    driver: bridge
